// Generated by Skyramp v1.3.23 on 2026-05-10 21:01:28.741053809 +0000 UTC m=+164.476594470
// Command: skyramp generate contract rest http://localhost:5001/api/auth/callback/google \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output auth_callback_google_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--provider \
// 		--query-params error=access_denied \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5001");

// contract test for /api/auth/callback/google GET
test('testGoogleGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const googleGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/auth/callback/google",
        method: "GET",
        headers: headers,
        queryParams: {"error": "access_denied"}
    });

    // Generated Assertions
    expect(checkStatusCode(googleGetResponse, "20x"), 'status code').toBeTruthy();
});
