// Generated by Skyramp v1.3.23 on 2026-05-10 21:01:26.509250348 +0000 UTC m=+162.244791019
// Command: skyramp generate contract rest http://localhost:5001/api/bookings/{id} \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output bookings_get_id_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--path-params id=507f1f77bcf86cd799439011 \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5001");

// contract test for /api/bookings/{id} GET
test('testBookingsIdGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const id = "507f1f77bcf86cd799439011";

    // Execute Request
    const bookingsIdGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/bookings/{id}",
        method: "GET",
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(bookingsIdGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(bookingsIdGetResponse, "_id")).not.toBeNull();
    expect(getValue(bookingsIdGetResponse, "createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(bookingsIdGetResponse, "totalCost")).toBeGreaterThanOrEqual(0);
    expect(getValue(bookingsIdGetResponse, "refundAmount")).toBeGreaterThanOrEqual(0);
    expect(getValue(bookingsIdGetResponse, "hotelId")).not.toBeNull();
});
