// Generated by Skyramp v1.3.23 on 2026-05-10 19:30:37.102955666 +0000 UTC m=+529.041059470
// Command: skyramp generate contract rest http://localhost:5000/api/bookings/{id} \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method DELETE \
// 		--output bookings_delete_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--path-params id=a1b2c3d4e5f6a1b2c3d4e5f6 \
// 		--provider \
// 		--response-status-code 404 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5000");

// contract test for /api/bookings/{id} DELETE
test('testBookingsIdDelete', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const id = "a1b2c3d4e5f6a1b2c3d4e5f6";

    // Execute Request
    const bookingsIdDeleteResponse = await client.sendRequest({
        url: URL,
        path: "/api/bookings/{id}",
        method: "DELETE",
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(bookingsIdDeleteResponse.statusCode, 'status code').toBe(404);
    expect(getValue(bookingsIdDeleteResponse, "message")).toBe("Booking not found");
});
