// Generated by Skyramp v1.3.23 on 2026-05-10 20:28:45.884301936 +0000 UTC m=+211.917438945
// Command: skyramp generate contract rest http://localhost:5001/api/business-insights/dashboard/public \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output dashboard_public_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5001");

// contract test for /api/business-insights/dashboard/public GET
test('testPublicGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const publicGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/business-insights/dashboard/public",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(publicGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(publicGetResponse, "overview.totalHotels")).toBeGreaterThanOrEqual(0);
    expect(getValue(publicGetResponse, "overview.totalUsers")).toBeGreaterThanOrEqual(0);
    expect(getValue(publicGetResponse, "overview.totalBookings")).toBeGreaterThanOrEqual(0);
    expect(getValue(publicGetResponse, "overview.recentBookings")).toBeGreaterThanOrEqual(0);
    expect(getValue(publicGetResponse, "overview.totalRevenue")).toBeGreaterThanOrEqual(0);
    expect(getValue(publicGetResponse, "overview.recentRevenue")).toBeGreaterThanOrEqual(0);
    expect(getValue(publicGetResponse, "popularDestinations")).not.toBeNull();
    expect(getValue(publicGetResponse, "dailyBookings")).not.toBeNull();
    expect(getValue(publicGetResponse, "hotelPerformance")).not.toBeNull();
    expect(getValue(publicGetResponse, "lastUpdated")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
});
