// Generated by Skyramp v1.3.23 on 2026-05-10 20:28:47.639742232 +0000 UTC m=+213.672879271
// Command: skyramp generate contract rest http://localhost:5000/api/business-insights/forecast/public \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output forecast_public_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5000");

// contract test for /api/business-insights/forecast/public GET
test('testPublicGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const publicGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/business-insights/forecast/public",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(publicGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(publicGetResponse, "historical")).not.toBeNull();
    expect(getValue(publicGetResponse, "forecasts")).not.toBeNull();
    expect(getValue(publicGetResponse, "forecasts.0.bookings")).toBeGreaterThanOrEqual(0);
    expect(getValue(publicGetResponse, "forecasts.0.revenue")).toBeGreaterThanOrEqual(0);
    expect(getValue(publicGetResponse, "forecasts.0.confidence")).toBeGreaterThanOrEqual(0.6);
    expect(getValue(publicGetResponse, "forecasts.0.week")).toMatch(/^\d{4}-\d{2}-\d{2}/);
    expect(getValue(publicGetResponse, "seasonalGrowth")).toBeDefined();
    expect(getValue(publicGetResponse, "lastUpdated")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
});
