// Generated by Skyramp v1.3.23 on 2026-05-10 19:45:43.210081103 +0000 UTC m=+274.301391539
// Command: skyramp generate contract rest http://localhost:5001/api/health/detailed \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output health_detailed_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5001");

// contract test for /api/health/detailed GET
test('testDetailedGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const detailedGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/health/detailed",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(detailedGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(detailedGetResponse, "status")).toBe("healthy");
    expect(getValue(detailedGetResponse, "timestamp")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(detailedGetResponse, "system.platform")).not.toBeNull();
    expect(getValue(detailedGetResponse, "system.arch")).not.toBeNull();
    expect(getValue(detailedGetResponse, "system.nodeVersion")).not.toBeNull();
    expect(getValue(detailedGetResponse, "system.pid")).toBeGreaterThan(0);
    expect(getValue(detailedGetResponse, "performance.memory.heapUsed")).toBeGreaterThan(0);
    expect(getValue(detailedGetResponse, "performance.memory.heapTotal")).toBeGreaterThan(0);
    expect(getValue(detailedGetResponse, "performance.uptime")).toBeGreaterThanOrEqual(0);
    expect(getValue(detailedGetResponse, "database.status")).not.toBeNull();
    expect(getValue(detailedGetResponse, "database.readyState")).toBeGreaterThanOrEqual(0);
});
