// Generated by Skyramp v1.3.23 on 2026-05-10 21:01:31.114948088 +0000 UTC m=+166.850488749
// Command: skyramp generate contract rest http://localhost:5001/api/hotels/search \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output hotels_search_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--provider \
// 		--query-params page=1 \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5001");

// contract test for /api/hotels/search GET
test('testSearchGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const searchGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/hotels/search",
        method: "GET",
        headers: headers,
        queryParams: {"page": "1"}
    });

    // Generated Assertions
    expect(searchGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(searchGetResponse, "pagination.page")).toBe(1);
    expect(getValue(searchGetResponse, "pagination.total")).toBeGreaterThanOrEqual(0);
    expect(getValue(searchGetResponse, "pagination.pages")).toBeGreaterThanOrEqual(0);
    expect(getValue(searchGetResponse, "data")).not.toBeNull();
    expect(getValue(searchGetResponse, "data").length).toBeLessThanOrEqual(5);
});
