// Generated by Skyramp v1.3.23 on 2026-05-10 19:28:09.239404686 +0000 UTC m=+381.177508491
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output id_delete_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend/scenario_id-delete-lifecycle.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5001");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const registerPostRequestBody = `{
            "email": "skyramptest@example.com",
            "firstName": "TestUser",
            "lastName": "Skyramp",
            "password": "password123"
        }`
    
    // Execute Request
    let registerPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/users/register",
        method:"POST",
        body:registerPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(registerPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(registerPostResponse, "message")).toBe("User registered OK");

    // Request Body
    const loginPostRequestBody = `{
            "email": "skyramptest@example.com",
            "password": "password123"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/auth/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(loginPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(loginPostResponse, "message")).toBe("Login successful");
    expect(getValue(loginPostResponse, "userId")).not.toBeNull();
    expect(getValue(loginPostResponse, "token")).not.toBeNull();

    // Execute Request
    let bookings000000000000000000000001DeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/bookings/000000000000000000000001",
        method:"DELETE",
        headers:headers
    });

    // Generated Assertions
    expect(bookings000000000000000000000001DeleteResponse.statusCode, 'status code').toBe(404);
    expect(getValue(bookings000000000000000000000001DeleteResponse, "message")).toBe("Booking not found");
});

