// Generated by Skyramp v1.3.23 on 2026-05-10 19:27:58.113348707 +0000 UTC m=+370.051452522
// Command: skyramp generate contract rest http://localhost:5000/api/auth/logout \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output logout_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5000");

// contract test for /api/auth/logout POST
test('testLogoutPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const logoutPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/auth/logout",
        method: "POST",
        headers: headers
    });

    // Generated Assertions
    expect(logoutPostResponse.statusCode, 'status code').toBe(200);
});
