// Generated by Skyramp v1.3.23 on 2026-05-10 20:28:43.94435224 +0000 UTC m=+209.977489258
// Command: skyramp generate contract rest http://localhost:5001/api/users/me \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output users_me_contract_test.spec.ts \
// 		--output-dir /home/runner/work/hotel-booking-2000/hotel-booking-2000/tests/hotel-booking-backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5001");

// contract test for /api/users/me GET
test('testMeGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const meGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/users/me",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(meGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(meGetResponse, "_id")).not.toBeNull();
    expect(getValue(meGetResponse, "email")).toMatch(/@/);
    expect(getValue(meGetResponse, "firstName")).not.toBeNull();
    expect(getValue(meGetResponse, "lastName")).not.toBeNull();
    expect(getValue(meGetResponse, "password")).toBeUndefined();
});
